# Generated by Django 4.1.6 on 2023-02-15 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_advert_created_at_advert_host'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='year',
            field=models.IntegerField(default='2020'),
        ),
    ]
