# Generated by Django 4.1.6 on 2023-02-24 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_advert_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='host',
            field=models.CharField(max_length=50),
        ),
    ]
