# Generated by Django 4.1.6 on 2023-05-03 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_advert_host'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Room',
        ),
    ]
