# Generated by Django 4.2.1 on 2023-06-12 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_delete_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='colour',
            field=models.CharField(default='Black', max_length=10),
        ),
        migrations.AddField(
            model_name='advert',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='advert',
            name='doors',
            field=models.IntegerField(default='4'),
        ),
        migrations.AddField(
            model_name='advert',
            name='engine_size',
            field=models.IntegerField(default='1'),
        ),
        migrations.AddField(
            model_name='advert',
            name='fuel',
            field=models.CharField(default='Petrol', max_length=10),
        ),
        migrations.AddField(
            model_name='advert',
            name='location',
            field=models.CharField(default='Dublin', max_length=20),
        ),
        migrations.AddField(
            model_name='advert',
            name='mileage',
            field=models.IntegerField(default='1000'),
        ),
        migrations.AddField(
            model_name='advert',
            name='price',
            field=models.IntegerField(default='1000'),
        ),
        migrations.AddField(
            model_name='advert',
            name='transmission',
            field=models.CharField(default='Manual', max_length=50),
        ),
        migrations.AddField(
            model_name='advert',
            name='username',
            field=models.CharField(default='', max_length=50),
        ),
    ]
