# Generated by Django 4.2.1 on 2023-06-12 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_advert_colour_advert_description_advert_doors_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advert',
            old_name='engine_size',
            new_name='engine',
        ),
    ]
