# Generated by Django 4.2.1 on 2023-06-12 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_engine_size_advert_engine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advert',
            name='created_at',
        ),
    ]
