# Generated by Django 4.2.1 on 2023-06-14 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_advert_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='price',
            field=models.IntegerField(default='0'),
        ),
    ]
